### ISSUE TITLE
[BUG] Fix parameter normalization

### ISSUE THREAD

**Issue by jholland918** [Mastercard/oauth1-signer-csharp#14]
**Description**
I'm trying to call a third-party API using this library to sign my requests, but my requests fail due to the signature being rejected. The third party provided me a working C# code sample that uses an old [MasterCard-Core](https://www.nuget.org/packages/MasterCard-Core/) NuGet package to sign requests. This old NuGet package links to the [Mastercard/sdk-core-csharp](https://github.com/Mastercard/sdk-core-csharp) repository, which no longer exists. I was able to find a recent fork at [bstriche/sdk-core-csharp](https://github.com/bstriche/sdk-core-csharp) to compare implementation differences between the old and new source code.

This library no longer percent encodes OAuth parameters during parameter normalization. The old one encoded oauth parameters [here](https://github.com/bstriche/sdk-core-csharp/blob/master/Sources/MasterCard/Core/Util.cs#L163). I forked this repository and added back this behavior, now my signatures are no longer rejected by this third-party API I'm integrating with.

I reviewed some OAuth 1 documentation at [3.4.1.3.2.  Parameters Normalization](https://datatracker.ietf.org/doc/html/rfc5849#section-3.4.1.3.2), [Appendix A.1. Example PUT Request](https://tools.ietf.org/id/draft-eaton-oauth-bodyhash-00.html#parameter), and [Twitter Developer Platform > Authentication > OAuth 1.0a](https://developer.twitter.com/en/docs/authentication/oauth-1-0a/creating-a-signature). It seems this behavior should be migrated into the new `Mastercard/oauth1-signer-csharp` to adhere to the spec.

**Related issues/PRs**
This may be the same issue as https://github.com/Mastercard/oauth1-signer-csharp/issues/2

**Suggest a fix/enhancement**
I've created a fork with a change and a unit test that fixes the issue for my needs here: https://github.com/jholland918/oauth1-signer-csharp

**Comment by karlismea** [comment]
I agree. It would be good to have it fixed.

**Comment by danny-gallagher** [comment]
Hi @jholland918, Thanks for the feedback. We recognise that there may be some work needed to conform to the OAuth 1.0a spec. 

However, because the OAuth signing libraries were developed to be used exclusively with Mastercard APIs, and it doesn't seem like the current version of the library is suffering from any issues in this regard, we cannot consider this a priority for the time being.

I'm closing this issue, but please note we will add this item to our backlog (as well as all of the other support OAuth signer languages).
