### ISSUE TITLE
Special characters encoding in oauth_body_hash

### ISSUE THREAD

**Issue by sergiomiguelinacio** [Mastercard/oauth1-signer-csharp#2]
Hi,
I was testing your libraries, both Java and C# and I am retrieving different results.

While in Java I can complete a request with 200 OK and my oauth_body_hash has the value of 47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU= ,

In C# I receive a 401 Unauthorized and my oauth_body_hash has the value of 47DEQpj8HBSa%2B%2FTImW%2B5JCeuQeRkm5NMpJWZG3hSuFU%3D .

I am using the OAuth.GetAuthorizationHeader method, as you can see below:
`HttpClient client = new HttpClient();`
`string authHeader = OAuth.GetAuthorizationHeader(url, "GET", null, Encoding.UTF8, consumerKey, signingKey);`
`client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("OAuth", authHeader.Replace("OAuth ", string.Empty));`

**Comment by jaaufauvre** [comment]
Hi Sergio, thanks for the feedback. Can you please tell the service/API you are trying to consume?

**Comment by sergiomiguelinacio** [comment]
The service is get cards by account 

/restservices/accounts/{accountID}/cards?requestID={requestID}

**Comment by sergiomiguelinacio** [comment]
Hi!

Any update?

Best Regards,
Sérgio Silva

**Comment by jaaufauvre** [comment]
Hi @sergiomiguelinacio,

Sorry for the late response, I missed the notification somehow 🤔

The `oauth_body_hash` encoding looks different indeed, we are going to look at this, but this shouldn't be a problem for our authentication gateway. That's the reason why I was asking previously which Mastercard API your were trying to consume so that we can try to reproduce the `Unauthorized` error.

Can you please send a link to the API? (I can't find what `/restservices/accounts/` is).

Thanks!

**Comment by jaaufauvre** [comment]
I'm closing this one, as this package should work with Mastercard APIs. The issue can be reopened if needed.
