### ISSUE TITLE
OAuth Signature parameter failed verification

### ISSUE THREAD

**Issue by ggbbeyou** [Mastercard/oauth1-signer-csharp#21]
![1](https://github.com/Mastercard/oauth1-signer-csharp/assets/5516762/d33eaa58-0f4a-49c2-8122-0bb63898d8eb)

my code :
public static RSA GetRSACryptoServiceProvider(string privateKeyPath, string privateKeyPassword)
{
    var certificate = new X509Certificate2(privateKeyPath, privateKeyPassword, X509KeyStorageFlags.Exportable);
    var privateKey = certificate.GetRSAPrivateKey();

    return privateKey!;
}
public async Task<ApiResponse> AddCheckOutAsync(AddCheckoutRequest postData, string memberId)
{
    var apiUrl = "https://sandbox.api.mastercard.com/srci/api/checkout";

    // load 
    var consumerKey = "key";

    var privateKeyPath = "test-sandbox-signing.p12";

    var privateKeyPassword = "123456";

    var rsa = OAuthSignatureGenerator.GetRSACryptoServiceProvider(privateKeyPath, privateKeyPassword);

    var serializedData = System.Text.Json.JsonSerializer.Serialize(postData);

    var header = OAuth.GetAuthorizationHeader(apiUrl, HttpMethod.Post.ToString(), serializedData, Encoding.UTF8, consumerKey, rsa);      
     
    var content = new StringContent(serializedData, Encoding.UTF8, "application/json");

    HttpClient _client = new HttpClient();

    _client.DefaultRequestHeaders.Add("X-Openapi-Clientid", memberId);
    _client.DefaultRequestHeaders.Add("Authorization", header);

    var response = await _client.PostAsync(apiUrl, content);             

    var responseContent = await response.Content.ReadAsStringAsync();

    var testResult = responseContent;
    return await ApiResponseFactory.Data(responseContent);
}

**Comment by ShimonaR-MC** [comment]
Hi @ggbbeyou
We expect that GitHub should be used for either submitting feature requests or for reporting bugs.

The issue reported seems to be an issue you face while integrating with Unified Checkout Solutions, rather than a bug in this project. We suggest you request assistance as documented [here](https://developer.mastercard.com/unified-checkout-solutions/documentation/support/#assistance). You may also refer to [this](https://developer.mastercard.com/support) to seek help from the support team.

Alternatively you may refer to [gateway error codes] (https://developer.mastercard.com/platform/documentation/security-and-authentication/gateway-error-codes/) which documents some of the common error codes and possible resolutions.
